# CMake generated Testfile for 
# Source directory: /Users/mauricioapaza/Desktop/Build_octree/cmake-3.27.6/Tests/ObjCXX
# Build directory: /Users/mauricioapaza/Desktop/Build_octree/cmake-3.27.6/Tests/ObjCXX
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[ObjCXX.ObjC++]=] "/Users/mauricioapaza/Desktop/Build_octree/cmake-3.27.6/bin/ctest" "--build-and-test" "/Users/mauricioapaza/Desktop/Build_octree/cmake-3.27.6/Tests/ObjCXX/ObjC++" "/Users/mauricioapaza/Desktop/Build_octree/cmake-3.27.6/Tests/ObjCXX/ObjC++" "--build-two-config" "--build-generator" "Unix Makefiles" "--build-makeprogram" "/usr/bin/make" "--build-project" "ObjC++" "--build-options" "--test-command" "ObjC++")
set_tests_properties([=[ObjCXX.ObjC++]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/mauricioapaza/Desktop/Build_octree/cmake-3.27.6/Tests/CMakeLists.txt;9;add_test;/Users/mauricioapaza/Desktop/Build_octree/cmake-3.27.6/Tests/ObjCXX/CMakeLists.txt;1;ADD_TEST_MACRO;/Users/mauricioapaza/Desktop/Build_octree/cmake-3.27.6/Tests/ObjCXX/CMakeLists.txt;0;")
add_test([=[ObjCXX.simple-build-test]=] "/Users/mauricioapaza/Desktop/Build_octree/cmake-3.27.6/bin/ctest" "--build-and-test" "/Users/mauricioapaza/Desktop/Build_octree/cmake-3.27.6/Tests/ObjCXX/simple-build-test" "/Users/mauricioapaza/Desktop/Build_octree/cmake-3.27.6/Tests/ObjCXX/simple-build-test" "--build-two-config" "--build-generator" "Unix Makefiles" "--build-makeprogram" "/usr/bin/make" "--build-project" "simple-build-test" "--build-options" "--test-command" "simple-build-test")
set_tests_properties([=[ObjCXX.simple-build-test]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/mauricioapaza/Desktop/Build_octree/cmake-3.27.6/Tests/CMakeLists.txt;9;add_test;/Users/mauricioapaza/Desktop/Build_octree/cmake-3.27.6/Tests/ObjCXX/CMakeLists.txt;2;ADD_TEST_MACRO;/Users/mauricioapaza/Desktop/Build_octree/cmake-3.27.6/Tests/ObjCXX/CMakeLists.txt;0;")
add_test([=[ObjCXX.cxx-file-extension-test]=] "/Users/mauricioapaza/Desktop/Build_octree/cmake-3.27.6/bin/ctest" "--build-and-test" "/Users/mauricioapaza/Desktop/Build_octree/cmake-3.27.6/Tests/ObjCXX/cxx-file-extension-test" "/Users/mauricioapaza/Desktop/Build_octree/cmake-3.27.6/Tests/ObjCXX/cxx-file-extension-test" "--build-two-config" "--build-generator" "Unix Makefiles" "--build-makeprogram" "/usr/bin/make" "--build-project" "cxx-file-extension-test" "--build-options" "--test-command" "cxx-file-extension-test")
set_tests_properties([=[ObjCXX.cxx-file-extension-test]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/mauricioapaza/Desktop/Build_octree/cmake-3.27.6/Tests/CMakeLists.txt;9;add_test;/Users/mauricioapaza/Desktop/Build_octree/cmake-3.27.6/Tests/ObjCXX/CMakeLists.txt;3;ADD_TEST_MACRO;/Users/mauricioapaza/Desktop/Build_octree/cmake-3.27.6/Tests/ObjCXX/CMakeLists.txt;0;")
add_test([=[ObjCXX.objcxx-file-extension-test]=] "/Users/mauricioapaza/Desktop/Build_octree/cmake-3.27.6/bin/ctest" "--build-and-test" "/Users/mauricioapaza/Desktop/Build_octree/cmake-3.27.6/Tests/ObjCXX/objcxx-file-extension-test" "/Users/mauricioapaza/Desktop/Build_octree/cmake-3.27.6/Tests/ObjCXX/objcxx-file-extension-test" "--build-two-config" "--build-generator" "Unix Makefiles" "--build-makeprogram" "/usr/bin/make" "--build-project" "objcxx-file-extension-test" "--build-options" "--test-command" "objcxx-file-extension-test")
set_tests_properties([=[ObjCXX.objcxx-file-extension-test]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/mauricioapaza/Desktop/Build_octree/cmake-3.27.6/Tests/CMakeLists.txt;9;add_test;/Users/mauricioapaza/Desktop/Build_octree/cmake-3.27.6/Tests/ObjCXX/CMakeLists.txt;4;ADD_TEST_MACRO;/Users/mauricioapaza/Desktop/Build_octree/cmake-3.27.6/Tests/ObjCXX/CMakeLists.txt;0;")
add_test([=[ObjCXX.cxx-as-objcxx]=] "/Users/mauricioapaza/Desktop/Build_octree/cmake-3.27.6/bin/ctest" "--build-and-test" "/Users/mauricioapaza/Desktop/Build_octree/cmake-3.27.6/Tests/ObjCXX/cxx-as-objcxx" "/Users/mauricioapaza/Desktop/Build_octree/cmake-3.27.6/Tests/ObjCXX/cxx-as-objcxx" "--build-two-config" "--build-generator" "Unix Makefiles" "--build-makeprogram" "/usr/bin/make" "--build-project" "cxx-as-objcxx" "--build-options" "--test-command" "cxx-as-objcxx")
set_tests_properties([=[ObjCXX.cxx-as-objcxx]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/mauricioapaza/Desktop/Build_octree/cmake-3.27.6/Tests/CMakeLists.txt;9;add_test;/Users/mauricioapaza/Desktop/Build_octree/cmake-3.27.6/Tests/ObjCXX/CMakeLists.txt;5;ADD_TEST_MACRO;/Users/mauricioapaza/Desktop/Build_octree/cmake-3.27.6/Tests/ObjCXX/CMakeLists.txt;0;")
